use trident_fuzz::fuzzing::*;

#[derive(Default)]
pub struct FuzzAccounts {
    pub approved_funder: AccountsStorage,
    pub authority: AccountsStorage,
    pub borrower: AccountsStorage,
    pub borrower_collateral_ata: AccountsStorage,
    pub borrower_usdc_account: AccountsStorage,
    pub borrower_usdc_ata: AccountsStorage,
    pub bot_authority: AccountsStorage,
    pub bot_processor: AccountsStorage,
    pub bot_collateral_ata: AccountsStorage,
    pub bot_usdc_ata: AccountsStorage,
    pub caller: AccountsStorage,
    pub collateral_mint: AccountsStorage,
    pub collateral_registry: AccountsStorage,
    pub contract: AccountsStorage,
    pub contract_collateral_ata: AccountsStorage,
    // `*_usdc_ata` accounts are SPL token accounts used by invariant checks.
    // Older `*_usdc_account` storages remain for instruction fixtures that still
    // model arbitrary account inputs before the on-chain constraints reject them.
    pub contract_usdc_account: AccountsStorage,
    pub contract_usdc_ata: AccountsStorage,
    pub contribution: AccountsStorage,
    pub escrow: AccountsStorage,
    pub escrow_usdc_ata: AccountsStorage,
    pub depositor: AccountsStorage,
    pub depositor_usdc_ata: AccountsStorage,
    pub frontend_operator: AccountsStorage,
    pub frontend_usdc_ata: AccountsStorage,
    pub lender: AccountsStorage,
    pub lender_usdc_account: AccountsStorage,
    pub liquidator: AccountsStorage,
    pub operator: AccountsStorage,
    pub operator_auth: AccountsStorage,
    pub operations_fund: AccountsStorage,
    pub pool: AccountsStorage,
    pub pool_deposit: AccountsStorage,
    pub pool_vault: AccountsStorage,
    pub price_feed_account: AccountsStorage,
    pub processor: AccountsStorage,
    pub program_data: AccountsStorage,
    pub state: AccountsStorage,
    pub treasury: AccountsStorage,
    pub treasury_usdc_account: AccountsStorage,
    pub treasury_usdc_ata: AccountsStorage,
    pub usdc_mint: AccountsStorage,
}
